#!/bin/bash
# Created By: Nathan
# Created: 2025-Nov-05_07:38
#
# Last Modified: 2026-Jan-27 20:38

embeddedAnswer(){
    read -p "Do you want embedded styling (y/n): " choicePicked
    if [[ "$choicePicked" == "Y" || "$choicePicked" == "y" ]]
    then 
        cat ~/.config/tools/codeTemplates/templates/htmlExampleEmbedded > $filename
    elif [[ "$choicePicked" == "N" || "$choicePicked" == "n" ]];
    then
        cat ~/.config/tools/codeTemplates/templates/htmlExampleNoEmbedded > $filename
    else
        embeddedAnswer
    fi
} 

htmlCreate(){
    filename=$1
    creator=$2
    dateCreated=$3
    touch $filename
    embeddedAnswer 
        
    sed -i "3s/filename/$filename/" $filename
    sed -i "4s/Created .*/Created By: $creator/" $filename
    sed -i "5s/Created.*/Created: $dateCreated/" $filename
    sed -i "7s/Last.*/Last Modified: $dateCreated/" $filename


}
   
    

