#!/bin/bash
# Created By: Nathan
# Created: 2025-Nov-05_07:38
#
# Last Modified: 2025-Nov-05 08:10

htmlCreate(){
    filename=$1
    creator=$2
    dateCreated=$3
    touch $filename
    cat ~/codeTemplates/templates/htmlExample > $filename

    sed -i "3s/filename/$filename/" $filename
    sed -i "4s/Created .*/Created By: $creator/" $filename
    sed -i "5s/Created.*/Created: $dateCreated/" $filename
    sed -i "7s/Last.*/Last Modified: $dateCreated/" $filename


}
   
    

