#!/bin/bash
# Created: Nathan
# Created By: 2025-Nov-02_02:26
#
# Last Modified: 


linuxCreate(){
    filename=$1
    creator=$2
    dateCreated=$3

    touch $filename
    chmod 644 $filename

    cat ~/codeTemplates/templates/linuxExample $filename
    sed -i "2s/Created .*/$modifiedForm/" $filename
    sed -i "3s/Created: .*/Created: $dateCreated/" $filename
    sed -i "5s/[Ll]ast [Mm]odified: .*/Last Modified: $dateCreated/" $filename
}
