#!/bin/bash
# 
# Created: 2025-Nov-01 19:30
#
# Last Modified: 2025-Nov-05 08:13

source ~/codeTemplates/allTemplates
source ~/codeTemplates/linuxTemplate
source ~/codeTemplates/htmlTemplate
source ~/codeTemplates/menu

# Checks if things exist
fileCreated $1
filename=$fileCreated
dateCreated

if [ -e $filename ]
then
    # if file exists, changes date and time
    dateModified $filename
elif [ ! -f $filename ] 
then
    if [ -z $2 ]
    then 
        creatorName
    else 
        creators=$2
    fi
    
    case $filename in 
        *.sh) 
            creatorName $2
            creator=$creators
            linuxCreate $filename $creator $madeOn
            ;;
        *.html)
            creator=$creators
            htmlCreate $filename $creator $madeOn
            ;;
        *.sql)
            creator=$creators
            sqlCreate $filename $creator $madeOn
            ;;
        *)
            echo "Which template do you want? Type 0 for options?"
            read -p "Template Choice: " tempChoice
            main_menu $filename $creators $tempChoice $madeOn
            ;;
    esac
    read -p "What type of permission will you grant it? " perm
    checkPerms $filename $perm
fi


vim $filename
