#!/bin/bash
# Created By: Nathan
# Created: 2025-Nov-02_02:23 
#
# Last Modified: 2025-Nov-02_02:23

source ~/codeTemplates/allTemplates
source ~/codeTemplates/linuxTemplate


main_menu(){
    filename=$1
    creator=$2
    choice=$3
    dateCreated=$4

    case $choice in
        0)
            echo "1. Linux"
            read -p "Template Choice: " choice
            main_menu $filename $creator $choice $dateCreated
            ;;
        1)
            linuxCreate $filename $creator $dateCreated
            ;;
        *) 
            echo "Not an option, please try again or type 0 for the options: "
            read -rp "Template Choice: " choice
            main_menu $filename $creator $createdDate $choice $dateCreated
            ;;
    esac
}

# Check if permission is accurate
checkPerms(){
    filename=$1
    perms=$2
    case "$perms" in
        [0-7][0-7][0-7])
            chmod $perms $filename
            ;;
        *)
            echo "Invalid permission: $perms"
            read -p "Please try again with 3 digits ranging from 0-7 (ie 777): " perm
            checkPerms $filename $perm
            ;;
    esac
}
