#!/bin/bash
# Created By: Nathan
# Created: 2025-Nov-02_02:23 
#
# Last Modified: 2026-Jan-27 20:56

source ~/.config/tools/codeTemplates/allTemplates
source ~/.config/tools/codeTemplates/linuxTemplate
source ~/.config/tools/codeTemplates/htmlTemplate
source ~/.config/tools/codeTemplates/sqlTemplate

main_menu(){
    filename=$1
    creator=$2
    choice=$3
    dateCreated=$4

    case $choice in
        0)
            echo "1. Linux 2. HTML 3. SQL"
            read -p "Template Choice: " choice
            main_menu $filename $creator $choice $dateCreated
            ;;
        1)
            bashName="$filename.sh"
            linuxCreate $bashName $creator $dateCreated
            ;;
        2)
            htmlName="$filename.html"
            htmlCreate $htmlName $creator $dateCreated
            ;;
        3)
            sqlName="$filename.sql"
            sqlCreate $sqlName $creator $dateCreated
            ;;
        *) 
            echo "Not an option, please try again or type 0 for the options: "
            read -rp "Template Choice: " choice
            main_menu $filename $creator $createdDate $choice $dateCreated
            ;;
    esac
}

# Check if permission is accurate
checkPerms(){
    filename=$1
    perms=$2
    case "$perms" in
        [0-7][0-7][0-7])
            chmod $perms $filename
            ;;
        *)
            echo "Invalid permission: $perms"
            read -p "Please try again with 3 digits ranging from 0-7 (ie 777): " perm
            checkPerms $filename $perm
            ;;
    esac
}
